-- AlterTable
ALTER TABLE "TenantSettings" ADD COLUMN     "emailAbandonedBody" TEXT,
ADD COLUMN     "emailAbandonedDelayHours" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN     "emailAbandonedEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "emailAbandonedIncludeLogo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emailAbandonedIncludeSig" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emailAbandonedSubject" TEXT DEFAULT 'Complete your funding application',
ADD COLUMN     "emailInsufficientBanksBody" TEXT,
ADD COLUMN     "emailInsufficientBanksEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "emailInsufficientBanksIncludeLogo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emailInsufficientBanksIncludeSig" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emailInsufficientBanksSubject" TEXT DEFAULT 'We need more bank statements to process your application',
ADD COLUMN     "emailMinBankStatements" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "emailNoBanksBody" TEXT,
ADD COLUMN     "emailNoBanksEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "emailNoBanksIncludeLogo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emailNoBanksIncludeSig" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emailNoBanksSubject" TEXT DEFAULT 'Don''t forget to upload your bank statements',
ADD COLUMN     "smtpFrom" TEXT,
ADD COLUMN     "smtpFromName" TEXT,
ADD COLUMN     "smtpHost" TEXT,
ADD COLUMN     "smtpPass" TEXT,
ADD COLUMN     "smtpPort" INTEGER,
ADD COLUMN     "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpUser" TEXT;
